// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnOxt7F18hj4QCQykwtRPhgVWLt3utTdM',
    appId: '1:51654071473:web:58ce8787ddb4ba19f47e90',
    messagingSenderId: '51654071473',
    projectId: 'service-395901',
    authDomain: 'service-395901.firebaseapp.com',
    storageBucket: 'service-395901.appspot.com',
    measurementId: 'G-GSJGL4QVC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9NJ4VRMpXbC8pOot36fN75bUnjUdbusc',
    appId: '1:51654071473:android:566a590720366bdaf47e90',
    messagingSenderId: '51654071473',
    projectId: 'service-395901',
    storageBucket: 'service-395901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoqTFIJeq0P0cIHhwGix4POkOgZpmSJug',
    appId: '1:51654071473:ios:9961ec6e9fa9682ef47e90',
    messagingSenderId: '51654071473',
    projectId: 'service-395901',
    storageBucket: 'service-395901.appspot.com',
    iosClientId: '51654071473-jvt5adniqiesp0ph5egbrl7i47rbuobq.apps.googleusercontent.com',
    iosBundleId: 'com.example.localServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoqTFIJeq0P0cIHhwGix4POkOgZpmSJug',
    appId: '1:51654071473:ios:6d8f8987a2306d5df47e90',
    messagingSenderId: '51654071473',
    projectId: 'service-395901',
    storageBucket: 'service-395901.appspot.com',
    iosClientId: '51654071473-irc09pdlnqmn3h2qj86cuuc88hhkb4eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.localServices.RunnerTests',
  );
}
